-- ==============================================================================
-- 數位車庫 (Digital Garage) - PostgreSQL Database Schema
-- 版本：P2-2 (含車輛出廠日、公路使用養護安全管理費、週期規費與到期管理)
-- ==============================================================================

-- ==========================================
-- 0. CLEAN RESET (清空並重置所有視圖、表格與自訂型別)
-- ==========================================
DROP VIEW IF EXISTS "vehicle_timeline";
DROP TABLE IF EXISTS "RecurringExpenses" CASCADE;
DROP TABLE IF EXISTS "ModificationSettings" CASCADE;
DROP TABLE IF EXISTS "ModificationSettingSets" CASCADE;
DROP TABLE IF EXISTS "ModificationPhotos" CASCADE;
DROP TABLE IF EXISTS "Modifications" CASCADE;
DROP TABLE IF EXISTS "Reminders" CASCADE;
DROP TABLE IF EXISTS "MaintenancePhotos" CASCADE;
DROP TABLE IF EXISTS "MaintenanceRecords" CASCADE;
DROP TABLE IF EXISTS "Refuels" CASCADE;
DROP TABLE IF EXISTS "VehiclePhotos" CASCADE;
DROP TABLE IF EXISTS "Vehicles" CASCADE;

DROP TYPE IF EXISTS "recurring_expense_category" CASCADE;
DROP TYPE IF EXISTS "modification_category" CASCADE;
DROP TYPE IF EXISTS "fuel_type" CASCADE;
DROP TYPE IF EXISTS "maintenance_record_type" CASCADE;
DROP TYPE IF EXISTS "reminder_status" CASCADE;

-- 清空媒體儲存桶物件 (若存在)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'storage' AND table_name = 'objects') THEN
    DELETE FROM storage.objects WHERE bucket_id = 'vehicle-media';
  END IF;
END $$;


-- ==========================================
-- 1. ENUMS 定義
-- ==========================================
CREATE TYPE "modification_category" AS ENUM (
  'suspension', 'braking', 'engine', 'exhaust', 'intake',
  'wheels_tires', 'exterior', 'interior', 'electronics', 'other'
);

CREATE TYPE "fuel_type" AS ENUM (
  'gasoline_92', 'gasoline_95', 'gasoline_98', 'diesel',
  'premium_diesel', 'electric', 'hybrid', 'other'
);

CREATE TYPE "maintenance_record_type" AS ENUM (
  'maintenance', 'repair'
);

CREATE TYPE "reminder_status" AS ENUM (
  'active', 'paused'
);

-- 週期性規費類別 (燃料稅正名為公路使用養護安全管理費，簡稱公路養管費)
CREATE TYPE "recurring_expense_category" AS ENUM (
  'license_tax',           -- 牌照稅 (每年4月開徵)
  'road_maintenance_fee',  -- 公路使用養護安全管理費 (簡稱公路養管費，原燃料使用費，每年7月開徵)
  'inspection',            -- 定期檢驗 / 機車排氣定檢 (出廠日前後各1個月)
  'compulsory_insurance',  -- 強制汽車責任保險
  'liability_insurance',   -- 任意第三人責任險 / 車體險
  'other'                  -- 其他規費
);


-- ==========================================
-- 2. 資料表定義
-- ==========================================

-- 車輛表 (Vehicles)
CREATE TABLE "Vehicles" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL REFERENCES auth.users("id") ON DELETE CASCADE,
  "brand" varchar NOT NULL,
  "model" varchar NOT NULL,
  "vehicle_type" varchar NOT NULL CHECK ("vehicle_type" IN ('car', 'motorcycle', 'other')),
  "year" integer,
  "manufacture_date" date CHECK ("manufacture_date" IS NULL OR "manufacture_date" <= CURRENT_DATE),
  "registration_date" date CHECK ("registration_date" IS NULL OR "registration_date" <= CURRENT_DATE),
  "purchase_date" date,
  "purchase_price" decimal(12,2) CHECK ("purchase_price" IS NULL OR "purchase_price" >= 0),
  "fuel_type" fuel_type,
  "engine_displacement_cc" integer CHECK ("engine_displacement_cc" IS NULL OR "engine_displacement_cc" > 0),
  "license_plate" varchar,
  "initial_mileage" integer NOT NULL DEFAULT 0 CHECK ("initial_mileage" >= 0),
  "current_mileage" integer NOT NULL DEFAULT 0 CHECK ("current_mileage" >= 0),
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_vehicles_mileage_consistency CHECK ("current_mileage" >= "initial_mileage")
);

-- 車輛照片 (VehiclePhotos)
CREATE TABLE "VehiclePhotos" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" integer NOT NULL REFERENCES "Vehicles"("id") ON DELETE CASCADE,
  "url" varchar NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "is_cover" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- 加油紀錄 (Refuels)
CREATE TABLE "Refuels" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" integer NOT NULL REFERENCES "Vehicles"("id") ON DELETE CASCADE,
  "refuel_date" date NOT NULL,
  "mileage" integer NOT NULL CHECK ("mileage" >= 0),
  "volume" decimal(10,2) NOT NULL CHECK ("volume" > 0),
  "price_per_unit" decimal(10,2),
  "total_cost" decimal(10,2) NOT NULL CHECK ("total_cost" >= 0),
  "fuel_type" fuel_type NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- 保養與維修紀錄 (MaintenanceRecords)
CREATE TABLE "MaintenanceRecords" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" integer NOT NULL REFERENCES "Vehicles"("id") ON DELETE CASCADE,
  "record_type" maintenance_record_type NOT NULL,
  "item_name" varchar NOT NULL,
  "service_date" date NOT NULL,
  "mileage" integer NOT NULL CHECK ("mileage" >= 0),
  "cost" decimal(10,2) NOT NULL DEFAULT 0 CHECK ("cost" >= 0),
  "shop_name" varchar,
  "note" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- 保養維修照片 (MaintenancePhotos)
CREATE TABLE "MaintenancePhotos" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "maintenance_record_id" integer NOT NULL REFERENCES "MaintenanceRecords"("id") ON DELETE CASCADE,
  "url" varchar NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- 保養提醒 (Reminders)
CREATE TABLE "Reminders" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" integer NOT NULL REFERENCES "Vehicles"("id") ON DELETE CASCADE,
  "item_name" varchar NOT NULL,
  "interval_km" integer,
  "interval_months" integer,
  "base_mileage" integer,
  "base_date" date,
  "last_completed_mileage" integer,
  "last_completed_date" date,
  "last_maintenance_record_id" integer REFERENCES "MaintenanceRecords"("id") ON DELETE SET NULL,
  "status" reminder_status NOT NULL DEFAULT 'active',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_interval_not_both_null CHECK (
    "interval_km" IS NOT NULL OR "interval_months" IS NOT NULL
  )
);

-- 改裝品 (Modifications)
CREATE TABLE "Modifications" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" integer NOT NULL REFERENCES "Vehicles"("id") ON DELETE CASCADE,
  "item_name" varchar NOT NULL,
  "category" modification_category NOT NULL,
  "brand" varchar,
  "model" varchar,
  "purchase_price" decimal(10,2) CHECK ("purchase_price" IS NULL OR "purchase_price" >= 0),
  "install_price" decimal(10,2) CHECK ("install_price" IS NULL OR "install_price" >= 0),
  "purchase_date" date,
  "install_date" date,
  "install_mileage" integer CHECK ("install_mileage" IS NULL OR "install_mileage" >= 0),
  "shop_name" varchar,
  "note" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- 改裝照片 (ModificationPhotos)
CREATE TABLE "ModificationPhotos" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "modification_id" integer NOT NULL REFERENCES "Modifications"("id") ON DELETE CASCADE,
  "url" varchar NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "photo_type" varchar,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- 改裝調校版本組 (ModificationSettingSets)
CREATE TABLE "ModificationSettingSets" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "modification_id" integer NOT NULL REFERENCES "Modifications"("id") ON DELETE CASCADE,
  "name" varchar NOT NULL,
  "recorded_date" date NOT NULL DEFAULT CURRENT_DATE,
  "mileage" integer CHECK ("mileage" IS NULL OR "mileage" >= 0),
  "is_current" boolean NOT NULL DEFAULT false,
  "note" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- 改裝參數細項 (ModificationSettings)
CREATE TABLE "ModificationSettings" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "setting_set_id" integer NOT NULL REFERENCES "ModificationSettingSets"("id") ON DELETE CASCADE,
  "setting_name" varchar NOT NULL,
  "setting_value" varchar NOT NULL,
  "unit" varchar,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- 週期性規費與到期管理 (RecurringExpenses - P2-2)
CREATE TABLE "RecurringExpenses" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" integer NOT NULL REFERENCES "Vehicles"("id") ON DELETE CASCADE,
  "category" recurring_expense_category NOT NULL,
  "title" varchar(100) NOT NULL,
  "amount" decimal(12,2) NOT NULL DEFAULT 0 CHECK ("amount" >= 0),
  "paid_date" date NOT NULL,
  "coverage_start_date" date NOT NULL,
  "coverage_end_date" date NOT NULL,
  "notes" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_recurring_coverage_order CHECK ("coverage_end_date" >= "coverage_start_date")
);


-- ==========================================
-- 3. 索引與業務唯一性約束 (Indexes & Constraints)
-- ==========================================
CREATE INDEX idx_refuels_vehicle_id ON "Refuels" ("vehicle_id");
CREATE INDEX idx_maintenance_vehicle_id ON "MaintenanceRecords" ("vehicle_id");
CREATE INDEX idx_reminders_vehicle_id ON "Reminders" ("vehicle_id");
CREATE INDEX idx_modifications_vehicle_id ON "Modifications" ("vehicle_id");
CREATE INDEX idx_mod_settingsets_mod_id ON "ModificationSettingSets" ("modification_id");
CREATE INDEX idx_mod_settings_set_id ON "ModificationSettings" ("setting_set_id");

-- RecurringExpenses 專屬查詢與排序索引
CREATE INDEX idx_recurring_expenses_vehicle_id ON "RecurringExpenses" ("vehicle_id");
CREATE INDEX idx_recurring_expenses_coverage ON "RecurringExpenses" ("vehicle_id", "category", "coverage_end_date" DESC);
CREATE INDEX idx_recurring_expenses_paid_date ON "RecurringExpenses" ("vehicle_id", "paid_date");

-- 業務約束 1：同一個改裝品最多只能有一筆使用中的設定 (is_current = true)
CREATE UNIQUE INDEX idx_modification_single_current 
ON "ModificationSettingSets" ("modification_id") 
WHERE "is_current" = true;

-- 業務約束 2：每台車最多只能有一張封面首圖 (is_cover = true)
CREATE UNIQUE INDEX idx_vehicle_single_cover 
ON "VehiclePhotos" ("vehicle_id") 
WHERE "is_cover" = true;


-- ==========================================
-- 4. 自動更新 updated_at 觸發器 (Triggers)
-- ==========================================
CREATE OR REPLACE FUNCTION update_timestamp_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_vehicles_updated_at BEFORE UPDATE ON "Vehicles" FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();
CREATE TRIGGER update_refuels_updated_at BEFORE UPDATE ON "Refuels" FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();
CREATE TRIGGER update_maintenance_updated_at BEFORE UPDATE ON "MaintenanceRecords" FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();
CREATE TRIGGER update_reminders_updated_at BEFORE UPDATE ON "Reminders" FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();
CREATE TRIGGER update_modifications_updated_at BEFORE UPDATE ON "Modifications" FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();
CREATE TRIGGER update_mod_settingsets_updated_at BEFORE UPDATE ON "ModificationSettingSets" FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();
CREATE TRIGGER update_mod_settings_updated_at BEFORE UPDATE ON "ModificationSettings" FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();
CREATE TRIGGER update_recurring_expenses_updated_at BEFORE UPDATE ON "RecurringExpenses" FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();


-- ==========================================
-- 5. 開啟 RLS (Row Level Security) 與設定 Policies
-- ==========================================
ALTER TABLE "Vehicles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VehiclePhotos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Refuels" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MaintenanceRecords" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MaintenancePhotos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Reminders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Modifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ModificationPhotos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ModificationSettingSets" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ModificationSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecurringExpenses" ENABLE ROW LEVEL SECURITY;

-- 根表：車輛
CREATE POLICY "Users can manage own vehicles" ON "Vehicles"
FOR ALL TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 一層關聯表 (透過 vehicle_id 驗證)
CREATE POLICY "Users can manage own vehicle photos" ON "VehiclePhotos"
FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "VehiclePhotos".vehicle_id AND v.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "VehiclePhotos".vehicle_id AND v.user_id = auth.uid()));

CREATE POLICY "Users can manage own refuels" ON "Refuels"
FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "Refuels".vehicle_id AND v.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "Refuels".vehicle_id AND v.user_id = auth.uid()));

CREATE POLICY "Users can manage own maintenance records" ON "MaintenanceRecords"
FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "MaintenanceRecords".vehicle_id AND v.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "MaintenanceRecords".vehicle_id AND v.user_id = auth.uid()));

CREATE POLICY "Users can manage own reminders" ON "Reminders"
FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "Reminders".vehicle_id AND v.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "Reminders".vehicle_id AND v.user_id = auth.uid()));

CREATE POLICY "Users can manage own modifications" ON "Modifications"
FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "Modifications".vehicle_id AND v.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "Modifications".vehicle_id AND v.user_id = auth.uid()));

CREATE POLICY "Users can manage own recurring expenses" ON "RecurringExpenses"
FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "RecurringExpenses".vehicle_id AND v.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "RecurringExpenses".vehicle_id AND v.user_id = auth.uid()));

-- 二層關聯表 (MaintenancePhotos, ModificationPhotos, ModificationSettingSets)
CREATE POLICY "Users can manage own maintenance photos" ON "MaintenancePhotos"
FOR ALL TO authenticated
USING (EXISTS (
  SELECT 1 FROM "MaintenanceRecords" mr
  JOIN "Vehicles" v ON v.id = mr.vehicle_id
  WHERE mr.id = "MaintenancePhotos".maintenance_record_id AND v.user_id = auth.uid()
))
WITH CHECK (EXISTS (
  SELECT 1 FROM "MaintenanceRecords" mr
  JOIN "Vehicles" v ON v.id = mr.vehicle_id
  WHERE mr.id = "MaintenancePhotos".maintenance_record_id AND v.user_id = auth.uid()
));

CREATE POLICY "Users can manage own modification photos" ON "ModificationPhotos"
FOR ALL TO authenticated
USING (EXISTS (
  SELECT 1 FROM "Modifications" m
  JOIN "Vehicles" v ON v.id = m.vehicle_id
  WHERE m.id = "ModificationPhotos".modification_id AND v.user_id = auth.uid()
))
WITH CHECK (EXISTS (
  SELECT 1 FROM "Modifications" m
  JOIN "Vehicles" v ON v.id = m.vehicle_id
  WHERE m.id = "ModificationPhotos".modification_id AND v.user_id = auth.uid()
));

CREATE POLICY "Users can manage own modification setting sets" ON "ModificationSettingSets"
FOR ALL TO authenticated
USING (EXISTS (
  SELECT 1 FROM "Modifications" m
  JOIN "Vehicles" v ON v.id = m.vehicle_id
  WHERE m.id = "ModificationSettingSets".modification_id AND v.user_id = auth.uid()
))
WITH CHECK (EXISTS (
  SELECT 1 FROM "Modifications" m
  JOIN "Vehicles" v ON v.id = m.vehicle_id
  WHERE m.id = "ModificationSettingSets".modification_id AND v.user_id = auth.uid()
));

-- 三層關聯表 (ModificationSettings)
CREATE POLICY "Users can manage own modification settings" ON "ModificationSettings"
FOR ALL TO authenticated
USING (EXISTS (
  SELECT 1 FROM "ModificationSettingSets" mss
  JOIN "Modifications" m ON m.id = mss.modification_id
  JOIN "Vehicles" v ON v.id = m.vehicle_id
  WHERE mss.id = "ModificationSettings".setting_set_id AND v.user_id = auth.uid()
))
WITH CHECK (EXISTS (
  SELECT 1 FROM "ModificationSettingSets" mss
  JOIN "Modifications" m ON m.id = mss.modification_id
  JOIN "Vehicles" v ON v.id = m.vehicle_id
  WHERE mss.id = "ModificationSettings".setting_set_id AND v.user_id = auth.uid()
));


-- ==========================================
-- 6. 車輛動態時間軸 View (Timeline)
-- 包含 security_invoker 保證繼承 RLS，並做好 NULL 日期與金額容錯
-- 包含 5 大生命週期事件：加油、保養維修、改裝、購車入庫、週期規費
-- ==========================================
CREATE VIEW vehicle_timeline 
WITH (security_invoker = true) 
AS
  -- 1. 加油事件
  SELECT 
    vehicle_id, 
    'refuel' AS event_type, 
    id AS event_id, 
    refuel_date AS event_date, 
    mileage, 
    COALESCE(total_cost, 0) AS cost,
    fuel_type::text AS title,
    NULL::text AS description,
    created_at
  FROM "Refuels"

  UNION ALL

  -- 2. 維修/保養事件
  SELECT 
    vehicle_id, 
    record_type::text AS event_type, 
    id AS event_id, 
    service_date AS event_date, 
    mileage, 
    COALESCE(cost, 0) AS cost,
    item_name AS title,
    note AS description,
    created_at
  FROM "MaintenanceRecords"

  UNION ALL

  -- 3. 改裝事件 (優先安裝日，無安裝日降級為購買日，最後降級為建立建檔日)
  SELECT 
    vehicle_id, 
    'modification' AS event_type, 
    id AS event_id, 
    COALESCE(install_date, purchase_date, created_at::date) AS event_date, 
    install_mileage AS mileage, 
    (COALESCE(purchase_price, 0) + COALESCE(install_price, 0)) AS cost,
    item_name AS title,
    note AS description,
    created_at
  FROM "Modifications"

  UNION ALL

  -- 4. 車輛購入入庫事件 (僅當 purchase_date IS NOT NULL 時產生，禁止使用 created_at 假造)
  SELECT 
    id AS vehicle_id,
    'purchase' AS event_type,
    id AS event_id,
    purchase_date AS event_date,
    initial_mileage AS mileage,
    COALESCE(purchase_price, 0) AS cost,
    (brand || ' ' || model || ' 購入入庫') AS title,
    ('入庫基準里程: ' || initial_mileage || ' KM') AS description,
    created_at
  FROM "Vehicles"
  WHERE purchase_date IS NOT NULL

  UNION ALL

  -- 5. 週期規費事件 (牌照稅、公路養管費、定期檢驗、保險)
  -- 顯式指定 NULL::integer AS mileage 與 COALESCE(amount, 0) AS cost 確保 UNION 型別一致性
  SELECT 
    vehicle_id, 
    'recurring_expense' AS event_type, 
    id AS event_id, 
    paid_date AS event_date, 
    NULL::integer AS mileage, 
    COALESCE(amount, 0) AS cost,
    title,
    notes AS description,
    created_at
  FROM "RecurringExpenses";


-- ==========================================
-- 7. Storage Bucket 與存取安全政策
-- ==========================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('vehicle-media', 'vehicle-media', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public Read Access" ON storage.objects;
CREATE POLICY "Public Read Access" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'vehicle-media');

DROP POLICY IF EXISTS "Users can upload to own folder" ON storage.objects;
CREATE POLICY "Users can upload to own folder" 
ON storage.objects FOR INSERT TO authenticated 
WITH CHECK (
  bucket_id = 'vehicle-media' 
  AND (storage.foldername(name))[1] = auth.uid()::text
);

DROP POLICY IF EXISTS "Users can update own files" ON storage.objects;
CREATE POLICY "Users can update own files" 
ON storage.objects FOR UPDATE TO authenticated 
USING (
  bucket_id = 'vehicle-media' 
  AND (storage.foldername(name))[1] = auth.uid()::text
)
WITH CHECK (
  bucket_id = 'vehicle-media' 
  AND (storage.foldername(name))[1] = auth.uid()::text
);

DROP POLICY IF EXISTS "Users can delete own files" ON storage.objects;
CREATE POLICY "Users can delete own files" 
ON storage.objects FOR DELETE TO authenticated 
USING (
  bucket_id = 'vehicle-media' 
  AND (storage.foldername(name))[1] = auth.uid()::text
);
