-- ==========================================
-- 1. ENUMS 定義
-- ==========================================
CREATE TYPE "modification_category" AS ENUM (
  'suspension', 'braking', 'engine', 'exhaust', 'intake',
  'wheels_tires', 'exterior', 'interior', 'electronics', 'other'
);

CREATE TYPE "fuel_type" AS ENUM (
  'gasoline_92', 'gasoline_95', 'gasoline_98', 'diesel',
  'premium_diesel', 'electric', 'hybrid', 'other'
);

CREATE TYPE "maintenance_record_type" AS ENUM (
  'maintenance', 'repair'
);

CREATE TYPE "reminder_status" AS ENUM (
  'active', 'paused'
);


-- ==========================================
-- 2. 資料表定義
-- ==========================================

-- 車輛表
CREATE TABLE "Vehicles" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL REFERENCES auth.users("id") ON DELETE CASCADE,
  "brand" varchar NOT NULL,
  "model" varchar NOT NULL,
  "vehicle_type" varchar NOT NULL CHECK ("vehicle_type" IN ('car', 'motorcycle', 'other')),
  "year" integer,
  "purchase_date" date,
  "purchase_price" decimal(12,2) CHECK ("purchase_price" IS NULL OR "purchase_price" >= 0),
  "fuel_type" fuel_type,
  "engine_displacement_cc" integer CHECK ("engine_displacement_cc" IS NULL OR "engine_displacement_cc" > 0),
  "license_plate" varchar,
  "initial_mileage" integer NOT NULL DEFAULT 0 CHECK ("initial_mileage" >= 0),
  "current_mileage" integer NOT NULL DEFAULT 0 CHECK ("current_mileage" >= 0),
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_vehicles_mileage_consistency CHECK ("current_mileage" >= "initial_mileage")
);

-- 車輛照片
CREATE TABLE "VehiclePhotos" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" integer NOT NULL REFERENCES "Vehicles"("id") ON DELETE CASCADE,
  "url" varchar NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "is_cover" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- 加油紀錄
CREATE TABLE "Refuels" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" integer NOT NULL REFERENCES "Vehicles"("id") ON DELETE CASCADE,
  "refuel_date" date NOT NULL,
  "mileage" integer NOT NULL CHECK ("mileage" >= 0),
  "volume" decimal(10,2) NOT NULL CHECK ("volume" > 0),
  "price_per_unit" decimal(10,2),
  "total_cost" decimal(10,2) NOT NULL CHECK ("total_cost" >= 0),
  "fuel_type" fuel_type NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- 保養與維修紀錄
CREATE TABLE "MaintenanceRecords" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" integer NOT NULL REFERENCES "Vehicles"("id") ON DELETE CASCADE,
  "record_type" maintenance_record_type NOT NULL,
  "item_name" varchar NOT NULL,
  "service_date" date NOT NULL,
  "mileage" integer NOT NULL CHECK ("mileage" >= 0),
  "cost" decimal(10,2) NOT NULL DEFAULT 0 CHECK ("cost" >= 0),
  "shop_name" varchar,
  "note" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- 保養維修照片
CREATE TABLE "MaintenancePhotos" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "maintenance_record_id" integer NOT NULL REFERENCES "MaintenanceRecords"("id") ON DELETE CASCADE,
  "url" varchar NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- 保養提醒
CREATE TABLE "Reminders" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" integer NOT NULL REFERENCES "Vehicles"("id") ON DELETE CASCADE,
  "item_name" varchar NOT NULL,
  "interval_km" integer,
  "interval_months" integer,
  "base_mileage" integer,
  "base_date" date,
  "last_completed_mileage" integer,
  "last_completed_date" date,
  "last_maintenance_record_id" integer REFERENCES "MaintenanceRecords"("id") ON DELETE SET NULL,
  "status" reminder_status NOT NULL DEFAULT 'active',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  -- 限制：至少必須提供一種正整數週期 (公里或月份)
  CONSTRAINT chk_reminders_interval_valid CHECK (
    (interval_km IS NOT NULL AND interval_km > 0) OR 
    (interval_months IS NOT NULL AND interval_months > 0)
  )
);

-- 改裝品
CREATE TABLE "Modifications" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" integer NOT NULL REFERENCES "Vehicles"("id") ON DELETE CASCADE,
  "brand" varchar,
  "item_name" varchar NOT NULL,
  "model" varchar,
  "category" modification_category NOT NULL,
  "purchase_date" date,
  "install_date" date,
  "install_mileage" integer CHECK ("install_mileage" IS NULL OR "install_mileage" >= 0),
  "purchase_price" decimal(10,2) NOT NULL DEFAULT 0 CHECK ("purchase_price" >= 0),
  "install_price" decimal(10,2) NOT NULL DEFAULT 0 CHECK ("install_price" >= 0),
  "shop_name" varchar,
  "note" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- 改裝照片
CREATE TABLE "ModificationPhotos" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "modification_id" integer NOT NULL REFERENCES "Modifications"("id") ON DELETE CASCADE,
  "url" varchar NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "photo_type" varchar,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- 改裝設定組 (版本控制)
CREATE TABLE "ModificationSettingSets" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "modification_id" integer NOT NULL REFERENCES "Modifications"("id") ON DELETE CASCADE,
  "name" varchar NOT NULL,
  "recorded_date" date NOT NULL,
  "mileage" integer CHECK ("mileage" IS NULL OR "mileage" >= 0),
  "note" text,
  "is_current" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- 改裝細項參數
CREATE TABLE "ModificationSettings" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "setting_set_id" integer NOT NULL REFERENCES "ModificationSettingSets"("id") ON DELETE CASCADE,
  "setting_name" varchar NOT NULL,
  "setting_value" varchar NOT NULL,
  "unit" varchar,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);


-- ==========================================
-- 3. 索引與業務唯一約束 (Indexes & Constraints)
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_vehicles_user_id ON "Vehicles" ("user_id");
CREATE INDEX IF NOT EXISTS idx_vehicle_photos_vehicle_id ON "VehiclePhotos" ("vehicle_id");
CREATE INDEX IF NOT EXISTS idx_refuels_vehicle_id ON "Refuels" ("vehicle_id");
CREATE INDEX idx_refuels_vehicle_date ON "Refuels" ("vehicle_id", "refuel_date");
CREATE INDEX idx_refuels_vehicle_mileage ON "Refuels" ("vehicle_id", "mileage");
CREATE INDEX idx_maintenance_vehicle_id ON "MaintenanceRecords" ("vehicle_id");
CREATE INDEX idx_maintenance_vehicle_date ON "MaintenanceRecords" ("vehicle_id", "service_date");
CREATE INDEX idx_maintenance_vehicle_mileage ON "MaintenanceRecords" ("vehicle_id", "mileage");
CREATE INDEX idx_maintenance_photos_record_id ON "MaintenancePhotos" ("maintenance_record_id");
CREATE INDEX idx_reminders_vehicle_id ON "Reminders" ("vehicle_id");
CREATE INDEX idx_reminders_status ON "Reminders" ("status");
CREATE INDEX idx_modifications_vehicle_id ON "Modifications" ("vehicle_id");
CREATE INDEX idx_modifications_category ON "Modifications" ("category");
CREATE INDEX idx_modifications_vehicle_date ON "Modifications" ("vehicle_id", "install_date");
CREATE INDEX idx_mod_photos_mod_id ON "ModificationPhotos" ("modification_id");
CREATE INDEX idx_mod_setting_sets_mod_id ON "ModificationSettingSets" ("modification_id");
CREATE INDEX idx_mod_settings_set_id ON "ModificationSettings" ("setting_set_id");

-- 業務約束 1：同一個改裝品最多只能有一筆使用中的設定 (is_current = true)
CREATE UNIQUE INDEX idx_modification_single_current 
ON "ModificationSettingSets" ("modification_id") 
WHERE "is_current" = true;

-- 業務約束 2：每台車最多只能有一張封面首圖 (is_cover = true)
CREATE UNIQUE INDEX idx_vehicle_single_cover 
ON "VehiclePhotos" ("vehicle_id") 
WHERE "is_cover" = true;


-- ==========================================
-- 4. 自動更新 updated_at 觸發器 (Triggers)
-- ==========================================
CREATE OR REPLACE FUNCTION update_timestamp_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_vehicles_updated_at BEFORE UPDATE ON "Vehicles" FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();
CREATE TRIGGER update_refuels_updated_at BEFORE UPDATE ON "Refuels" FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();
CREATE TRIGGER update_maintenance_updated_at BEFORE UPDATE ON "MaintenanceRecords" FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();
CREATE TRIGGER update_reminders_updated_at BEFORE UPDATE ON "Reminders" FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();
CREATE TRIGGER update_modifications_updated_at BEFORE UPDATE ON "Modifications" FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();
CREATE TRIGGER update_mod_settingsets_updated_at BEFORE UPDATE ON "ModificationSettingSets" FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();
CREATE TRIGGER update_mod_settings_updated_at BEFORE UPDATE ON "ModificationSettings" FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();


-- ==========================================
-- 5. 開啟 RLS (Row Level Security) 與設定 Policies
-- ==========================================
ALTER TABLE "Vehicles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VehiclePhotos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Refuels" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MaintenanceRecords" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MaintenancePhotos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Reminders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Modifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ModificationPhotos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ModificationSettingSets" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ModificationSettings" ENABLE ROW LEVEL SECURITY;

-- 根表：車輛
CREATE POLICY "Users can manage own vehicles" ON "Vehicles"
FOR ALL TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 一層關聯表 (透過 vehicle_id 驗證)
CREATE POLICY "Users can manage own vehicle photos" ON "VehiclePhotos"
FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "VehiclePhotos".vehicle_id AND v.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "VehiclePhotos".vehicle_id AND v.user_id = auth.uid()));

CREATE POLICY "Users can manage own refuels" ON "Refuels"
FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "Refuels".vehicle_id AND v.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "Refuels".vehicle_id AND v.user_id = auth.uid()));

CREATE POLICY "Users can manage own maintenance records" ON "MaintenanceRecords"
FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "MaintenanceRecords".vehicle_id AND v.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "MaintenanceRecords".vehicle_id AND v.user_id = auth.uid()));

CREATE POLICY "Users can manage own reminders" ON "Reminders"
FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "Reminders".vehicle_id AND v.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "Reminders".vehicle_id AND v.user_id = auth.uid()));

CREATE POLICY "Users can manage own modifications" ON "Modifications"
FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "Modifications".vehicle_id AND v.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM "Vehicles" v WHERE v.id = "Modifications".vehicle_id AND v.user_id = auth.uid()));

-- 兩層關聯表
CREATE POLICY "Users can manage own maintenance photos" ON "MaintenancePhotos"
FOR ALL TO authenticated
USING (EXISTS (
  SELECT 1 FROM "MaintenanceRecords" m JOIN "Vehicles" v ON v.id = m.vehicle_id
  WHERE m.id = "MaintenancePhotos".maintenance_record_id AND v.user_id = auth.uid()
))
WITH CHECK (EXISTS (
  SELECT 1 FROM "MaintenanceRecords" m JOIN "Vehicles" v ON v.id = m.vehicle_id
  WHERE m.id = "MaintenancePhotos".maintenance_record_id AND v.user_id = auth.uid()
));

CREATE POLICY "Users can manage own modification photos" ON "ModificationPhotos"
FOR ALL TO authenticated
USING (EXISTS (
  SELECT 1 FROM "Modifications" m JOIN "Vehicles" v ON v.id = m.vehicle_id
  WHERE m.id = "ModificationPhotos".modification_id AND v.user_id = auth.uid()
))
WITH CHECK (EXISTS (
  SELECT 1 FROM "Modifications" m JOIN "Vehicles" v ON v.id = m.vehicle_id
  WHERE m.id = "ModificationPhotos".modification_id AND v.user_id = auth.uid()
));

CREATE POLICY "Users can manage own modification setting sets" ON "ModificationSettingSets"
FOR ALL TO authenticated
USING (EXISTS (
  SELECT 1 FROM "Modifications" m JOIN "Vehicles" v ON v.id = m.vehicle_id
  WHERE m.id = "ModificationSettingSets".modification_id AND v.user_id = auth.uid()
))
WITH CHECK (EXISTS (
  SELECT 1 FROM "Modifications" m JOIN "Vehicles" v ON v.id = m.vehicle_id
  WHERE m.id = "ModificationSettingSets".modification_id AND v.user_id = auth.uid()
));

-- 三層關聯表 (ModificationSettings)
CREATE POLICY "Users can manage own modification settings" ON "ModificationSettings"
FOR ALL TO authenticated
USING (EXISTS (
  SELECT 1 FROM "ModificationSettingSets" mss
  JOIN "Modifications" m ON m.id = mss.modification_id
  JOIN "Vehicles" v ON v.id = m.vehicle_id
  WHERE mss.id = "ModificationSettings".setting_set_id AND v.user_id = auth.uid()
))
WITH CHECK (EXISTS (
  SELECT 1 FROM "ModificationSettingSets" mss
  JOIN "Modifications" m ON m.id = mss.modification_id
  JOIN "Vehicles" v ON v.id = m.vehicle_id
  WHERE mss.id = "ModificationSettings".setting_set_id AND v.user_id = auth.uid()
));


-- ==========================================
-- 6. 車輛動態時間軸 View (Timeline)
-- 包含 security_invoker 保證繼承 RLS，並做好 NULL 日期與金額容錯
-- ==========================================
DROP VIEW IF EXISTS vehicle_timeline;

CREATE VIEW vehicle_timeline 
WITH (security_invoker = true) 
AS
  -- 1. 加油事件
  SELECT 
    vehicle_id, 
    'refuel' AS event_type, 
    id AS event_id, 
    refuel_date AS event_date, 
    mileage, 
    COALESCE(total_cost, 0) AS cost,
    fuel_type::text AS title,
    NULL::text AS description,
    created_at
  FROM "Refuels"

  UNION ALL

  -- 2. 維修/保養事件
  SELECT 
    vehicle_id, 
    record_type::text AS event_type, 
    id AS event_id, 
    service_date AS event_date, 
    mileage, 
    COALESCE(cost, 0) AS cost,
    item_name AS title,
    note AS description,
    created_at
  FROM "MaintenanceRecords"

  UNION ALL

  -- 3. 改裝事件 (優先安裝日，無安裝日降級為購買日，最後降級為建立建檔日)
  SELECT 
    vehicle_id, 
    'modification' AS event_type, 
    id AS event_id, 
    COALESCE(install_date, purchase_date, created_at::date) AS event_date, 
    install_mileage AS mileage, 
    (COALESCE(purchase_price, 0) + COALESCE(install_price, 0)) AS cost,
    item_name AS title,
    note AS description,
    created_at
  FROM "Modifications"

  UNION ALL

  -- 4. 車輛購入入庫事件 (僅當 purchase_date IS NOT NULL 時產生，禁止使用 created_at 假造)
  SELECT 
    id AS vehicle_id,
    'purchase' AS event_type,
    id AS event_id,
    purchase_date AS event_date,
    initial_mileage AS mileage,
    COALESCE(purchase_price, 0) AS cost,
    (brand || ' ' || model || ' 購入入庫') AS title,
    ('入庫基準里程: ' || initial_mileage || ' KM') AS description,
    created_at
  FROM "Vehicles"
  WHERE purchase_date IS NOT NULL;


-- ==========================================
-- 7. Storage Bucket 與存取安全政策
-- ==========================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('vehicle-media', 'vehicle-media', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Read Access" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'vehicle-media');

CREATE POLICY "Users can upload to own folder" 
ON storage.objects FOR INSERT TO authenticated 
WITH CHECK (
  bucket_id = 'vehicle-media' 
  AND (storage.foldername(name))[1] = auth.uid()::text
);

CREATE POLICY "Users can update own files" 
ON storage.objects FOR UPDATE TO authenticated 
USING (
  bucket_id = 'vehicle-media' 
  AND (storage.foldername(name))[1] = auth.uid()::text
)
WITH CHECK (
  bucket_id = 'vehicle-media' 
  AND (storage.foldername(name))[1] = auth.uid()::text
);

CREATE POLICY "Users can delete own files" 
ON storage.objects FOR DELETE TO authenticated 
USING (
  bucket_id = 'vehicle-media' 
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- ==========================================
-- 8. MIGRATION & BACKFILL: initial_mileage
-- ==========================================
-- 為既有資料庫新增 initial_mileage 欄位並執行既有資料回填
ALTER TABLE "Vehicles" ADD COLUMN IF NOT EXISTS "initial_mileage" integer NOT NULL DEFAULT 0 CHECK ("initial_mileage" >= 0);

-- 既有資料回填：設為 current_mileage 與現存所有紀錄（加油、保修、改裝）中最小里程兩者的較小者
UPDATE "Vehicles" v
SET "initial_mileage" = COALESCE(
  (
    SELECT LEAST(
      v."current_mileage",
      COALESCE(
        (
          SELECT MIN(m) FROM (
            SELECT "mileage" AS m FROM "Refuels" WHERE "vehicle_id" = v."id"
            UNION ALL
            SELECT "mileage" AS m FROM "MaintenanceRecords" WHERE "vehicle_id" = v."id"
            UNION ALL
            SELECT "install_mileage" AS m FROM "Modifications" WHERE "vehicle_id" = v."id" AND "install_mileage" IS NOT NULL
          ) sub
        ),
        v."current_mileage"
      )
    )
  ),
  v."current_mileage",
  0
);

-- ==========================================
-- 9. MIGRATION: P1 車輛生命週期紀錄 (Vehicle Lifecycle)
-- ==========================================
-- 為既有資料庫擴充車輛詳細欄位
ALTER TABLE "Vehicles"
  ADD COLUMN IF NOT EXISTS "vehicle_type" varchar NOT NULL DEFAULT 'car' CHECK ("vehicle_type" IN ('car', 'motorcycle', 'other')),
  ADD COLUMN IF NOT EXISTS "purchase_price" decimal(12,2) CHECK ("purchase_price" IS NULL OR "purchase_price" >= 0),
  ADD COLUMN IF NOT EXISTS "fuel_type" fuel_type,
  ADD COLUMN IF NOT EXISTS "engine_displacement_cc" integer CHECK ("engine_displacement_cc" IS NULL OR "engine_displacement_cc" > 0),
  ADD COLUMN IF NOT EXISTS "license_plate" varchar;

-- 移除 migration default，確保後續新增必須明確指定 vehicle_type
ALTER TABLE "Vehicles" ALTER COLUMN "vehicle_type" DROP DEFAULT;

-- 增加里程一致性約束
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'chk_vehicles_mileage_consistency'
  ) THEN
    ALTER TABLE "Vehicles"
      ADD CONSTRAINT chk_vehicles_mileage_consistency CHECK (current_mileage >= initial_mileage);
  END IF;
END $$;
